AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: go1.x
      Timeout: 180
      Handler: dist/handler
      Environment:
        Variables:
          ProjectID: !Ref ParamProjectID

Parameters:
  ParamProjectName:
    Type: String
  ParamProjectScope:
    Type: String
  ParamProjectID:
    Type: String
  ParamENV:
    Type: String

Outputs:
  ProjectID:
    Description: Project ID
    Value: !Ref ParamProjectID
  Function:
    Description: Function Name
    Value: !Ref Function
